name: Push test image to Docker Hub.
on:
  push:
    branch:
      - "main"

env:
  DOCKER_USER: lcnetdev
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB}}
  REPO_NAME: scriptshifter

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build the Docker image
        run: docker build . --tag $DOCKER_USER/$REPO_NAME:test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lcnetdev
          password: ${{ secrets.DOCKER_HUB }}

      - name: Push to Docker Hub
        run: docker push $DOCKER_USER/$REPO_NAME:test

