name: Push test image
on:
  push:
    branches:
      - "test"

env:
  DOCKER_USER: lcnetdev
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB}}
  REPO_NAME: scriptshifter

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: update version info
        run: |
          git status
          git describe --tags >| VERSION
          git rev-parse HEAD >> VERSION

      - name: Build the Docker image
        run: >
          docker build -f Dockerfile .
          --tag $DOCKER_USER/$REPO_NAME:${{ github.ref_name }}
          --tag $DOCKER_USER/$REPO_NAME:test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lcnetdev
          password: ${{ secrets.DOCKER_HUB }}

      - name: Push to Docker Hub
        run: docker push $DOCKER_USER/$REPO_NAME:test
