name: Push image to Docker Hub.
on:
  push:
    tags:
      - "v*.*.*"

env:
  DOCKER_USER: lcnetdev
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB}}
  REPO_NAME: scriptshifter

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: checkout yiddish submodules (1/2)
        uses: actions/checkout@v4
        with:
          repository: ibleaman/loshn-koydesh-pronunciation
          path: ext/yiddish/yiddish/submodules/loshn-koydesh-pronunciation

      - name: checkout yiddish submodules (2/2)
        uses: actions/checkout@v4
        with:
          repository: ibleaman/hasidify_lexicon
          path: ext/yiddish/yiddish/submodules/hasidify_lexicon

      - name: Build the Docker image
        run: >
          docker build . --tag $DOCKER_USER/$REPO_NAME:${{ github.ref_name }}
          --tag $DOCKER_USER/$REPO_NAME:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lcnetdev
          password: ${{ secrets.DOCKER_HUB }}

      - name: Push to Docker Hub
        run: docker push $DOCKER_USER/$REPO_NAME --all-tags
