name: Push image to Docker Hub.
on:
  push:
    tags:
      - "v*.*.*"

env:
  DOCKER_USER: lcnetdev
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB}}
  REPO_NAME: scriptshifter

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag $DOCKER_USER/$REPO_NAME:${{ github.ref_name }}
      - name: docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push to Docker Hub
        run: docker push $DOCKER_USER/$REPO_NAME:${{ github.ref_name }}
